# Nome e Porta [cite: 97, 99]
spring.application.name=checkpoint1
server.port=8085

# Conex�o com o banco H2 [cite: 101]
spring.datasource.url=jdbc:h2:file:~/testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Configura��es do JPA e Hibernate [cite: 103, 105, 107]
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Interface Web do Banco de Dados H2 [cite: 109]
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console